### ISSUE TITLE
Custom crop does not drop items.

### ISSUE THREAD

**Issue by Sigmenzzz** [Notenoughmail/KubeJS-TFC#10]
My scripts:

StartupEvents.registry("block",event => {
    event.create('chorus', 'tfc:crop')
	.stages(5)
	.noCollision()
	.hardness(0.4)
	.tagBlock('tfc:mineable_with_sharp_tool')
	.deadBlock(block => {
		block.hardness(0.4)
		block.noCollision()
		block.tagBlock('tfc:mineable_with_sharp_tool')
	})
	.productItem("minecraft:chorus_fruit")
    	.nutrient('nitrogen')
})

It can work well in kubejs_tfc-1.20.1-1.1.3, but it does not drop anything in kubejs_tfc-1.20.1-1.2.0.

**Comment by Notenoughmail** [comment]
Thanks for the report, I'll look into it soon as I can. Hopefully Friday or Saturday

**Comment by Notenoughmail** [comment]
the automatic loot tables generated for crops should now be used again by default in 1.2.1, if there are still issues, please let me know!
