### ISSUE TITLE
Custom crop does not drop items when it dead

### ISSUE THREAD

**Issue by Sigmenzzz** [Notenoughmail/KubeJS-TFC#12]
Yeah, it just like my last issue.

**Comment by Sigmenzzz** [comment]
Besides, I found more problem about crop: the double crop dosen't have loot table as before; the dead wild crop still use the model of mature one but not the dead one; the default crop only drop seeds regardless of maturity

**Comment by Notenoughmail** [comment]
alright, I *think* I've sorted out all the loot table problems with custom crops

could you elaborate a little on the model problems? wild crops don't have a dead block, so I'm unsure of what you're referring to there

**Comment by Sigmenzzz** [comment]
the wild crop will use the model of the dead one when it's not mature
but that's not the case now and makes it hard to identify the wild crop dead or not

**Comment by Sigmenzzz** [comment]
![屏幕截图 2024-10-28 145505](https://github.com/user-attachments/assets/bfad78e3-0f91-45a7-b485-432ea677b381)
just like this, the wild carrots in vanilla TFC are using the "dead model" in winter

**Comment by Sigmenzzz** [comment]
well, i added blockstates for it by myself, and it seems that model problem had be solved already

**Comment by Notenoughmail** [comment]
ah, yeah there's not a good way to automatically use the dead model for non-mature wild crops, since they aren't connected in scripts. so I'll have to add some methods to modify those and let people override them via other means, if needed, like you are now

**Comment by Notenoughmail** [comment]
Should be fixed in 1.2.2, in addition to some methods in wild crop builders to set the dead models
