### ISSUE TITLE
Method .withPreexistingItem() invalid in 1.20.1

### ISSUE THREAD

**Issue by Sigmenzzz** [Notenoughmail/KubeJS-TFC#13]
my scripts:
![屏幕截图 2024-10-29 193856](https://github.com/user-attachments/assets/02259e7d-c601-4bf5-b25b-14b8609a8152)

**Comment by Notenoughmail** [comment]
Fixed in dev, didn't realize that would *close* the issue

**Comment by Notenoughmail** [comment]
This should be fixed in 1.2.2
