### ISSUE TITLE
itemsize does not affect dynamic foods like firmalife pizza (1.20.1)

### ISSUE THREAD

**Issue by G93d14** [Notenoughmail/KubeJS-TFC#14]
event.itemSize('firmalife:food/raw_pizza', 'tiny', 'very_light')
event.itemSize('firmalife:food/cooked_pizza', 'tiny', 'very_light')
![image](https://github.com/user-attachments/assets/c7e647eb-f9d5-48be-93d2-8e7fb2ddb119)
please advice if and when possible.

**Comment by Notenoughmail** [comment]
it seems Firmalife's [builtin definition](https://github.com/eerussianguy/firmalife/blob/1.20.x/src/main/resources/data/firmalife/tfc/item_sizes/dynamic_foods.json) uses the item tag `firmalife:foods/dynamic` to define the size and weight of pizzas

you could try removing that tag from them, but I am unaware if that tag is used for other functionality elsewhere, if so you could overload the default definition with an ingredient that does not include pizzas
