### ISSUE TITLE
Custom worldgen defaults are not enable.

### ISSUE THREAD

**Issue by redstaroverplank** [Notenoughmail/KubeJS-TFC#15]
![image](https://github.com/user-attachments/assets/b89a18cb-fabf-436e-9d52-d3dfe3575cb9)
![image](https://github.com/user-attachments/assets/77700b99-8965-4454-9a41-3f2e04e4778f)
(P2 meant TFC still use them default setting)

**Comment by Notenoughmail** [comment]
that is not how those methods are used, in your case you should have either

```js
TFCEvents.defaultWorldSettings(event => {
  event.setSpawnDistance(2000)
  event.setSpawnCenterX(5000)
  event.setSpawnCenterZ(5000)
})
```

or, using beans

```js
TFCEvents.defaultWorldSettings(event => {
  event.spawnDistance = 2000
  event.spawnCenterX = 5000
  event.spawnCenterZ = 5000
})
```

**Comment by redstaroverplank** [comment]
All  right, thanks.
