### ISSUE TITLE
[Feature Request]A way to make items(from other mods) become rotten.

### ISSUE THREAD

**Issue by Tollainmear** [Notenoughmail/KubeJS-TFC#5]
Hi, first of all, I've been waiting for an update to 1.20 for a few days, so thank you for your work!

Since I couldn't find any contact channels, I opened this issue to ask for help in making foods from other mods putrefiable.

I'm not sure if this is possible, but thank you again for your awesome work!

**Comment by Notenoughmail** [comment]
Hey there! This is certainly possible

All of TFC's foods are defined through a [food item](https://terrafirmacraft.github.io/Documentation/1.20.x/data/custom/#food-items) json definition. I have an event (`TFCEvents.data` or `tfc.data` depending on version) for adding all of TFC's data types through js

Here's the documentation for [1.20](https://notenoughmail.github.io/kubejs_tfc/1.20.1/data/#food-items) on adding your own food items, which defines which items rot and how fast

For future note, a good place to contact me is in the dedicated KubeJS TFC forum in the [TFC Discord](https://discord.gg/PRuAKvY) content channel

**Comment by Tollainmear** [comment]
wow, that great! 
thank you and have a nice day! lol
