### ISSUE TITLE
Absence of useDurability in the heating recipe

### ISSUE THREAD

**Issue by Exzept1on** [Notenoughmail/KubeJS-TFC#6]
Default TFC recipe: 
![image](https://github.com/Notenoughmail/KubeJS-TFC/assets/52341158/d611cb53-b050-4a5d-8cdf-c50a80001e19)

But I can't make the same recipe by mod:
![image](https://github.com/Notenoughmail/KubeJS-TFC/assets/52341158/7ccb1378-2c0e-416e-9ac5-4d037f42546f)

**Comment by Notenoughmail** [comment]
Thanks for the report! This will be fixed in 1.0.3 which should being going out soon
