### ISSUE TITLE
Phosphorus does not apply to item (fertilizer data)

### ISSUE THREAD

**Issue by Exzept1on** [Notenoughmail/KubeJS-TFC#7]
My script:
![image](https://github.com/Notenoughmail/KubeJS-TFC/assets/52341158/0d38c0b7-9fdb-40c0-ad99-66e92941b6e5)

In game:
![image](https://github.com/Notenoughmail/KubeJS-TFC/assets/52341158/12c35be9-9a9f-4e91-8cb2-476e1944ebd9)

**Comment by Notenoughmail** [comment]
Thanks for the report! This will be fixed in 1.0.3 which should be going out soon

**Comment by Notenoughmail** [comment]
Alright, curse is being a pain, but its up on Modrinth, so I'll go ahead and close both issues
