### ISSUE TITLE
KubeJS TFC's type hints are incorrect.

### ISSUE THREAD

**Issue by EvanHsieh0415** [Notenoughmail/KubeJS-TFC#8]
[ItemProviderComponent.java#L54-L59](https://github.com/Notenoughmail/KubeJS-TFC/blob/2b982632585bc280c5d24b0aa76dedbb7e0e13e6/src/main/java/com/notenoughmail/kubejs_tfc/recipe/component/ItemProviderComponent.java#L54-L59)
```diff
- return TypeDescJS.any(
-                 TypeDescJS.STRING.or(ctx.javaType(ItemStack.class)),
-                 TypeDescJS.MAP.withGenerics(TypeDescJS.STRING.or(ctx.javaType(JsonObject.class)))
-         );
+ return TypeDescJS.any(
+                 TypeDescJS.STRING, 
+                 ctx.javaType(ItemStack.class), 
+                 TypeDescJS.MAP.withGenerics(
+                          TypeDescJS.STRING, 
+                          TypeDescJS.STRING.or(ctx.javaType(JsonObject.class))
+                 );
```

**Comment by Notenoughmail** [comment]
hmm, I don't know why I have a map description there, it should theoretically be an array type to match how it's [processed](https://github.com/Notenoughmail/KubeJS-TFC/blob/2b982632585bc280c5d24b0aa76dedbb7e0e13e6/src/main/java/com/notenoughmail/kubejs_tfc/util/implementation/ItemStackProviderJS.java#L37-L55). Would this work:
```diff
- return TypeDescJS.any(
-                 TypeDescJS.STRING.or(ctx.javaType(ItemStack.class)),
-                 TypeDescJS.MAP.withGenerics(TypeDescJS.STRING.or(ctx.javaType(JsonObject.class)))
-         );
+ return TypeDescJS.any(
+                 TypeDescJS.STRING, 
+                 ctx.javaType(ItemStack.class), 
+                 TypeDescJS.fixedArray(
+                         TypeDescJS.STRING,
+                         ctx.javaType(JsonObject.class)
+                 ));
```

**Comment by EvanHsieh0415** [comment]
> hmm, I don't know why I have a map description there, it should theoretically be an array type to match how it's [processed](https://github.com/Notenoughmail/KubeJS-TFC/blob/2b982632585bc280c5d24b0aa76dedbb7e0e13e6/src/main/java/com/notenoughmail/kubejs_tfc/util/implementation/ItemStackProviderJS.java#L37-L55). Would this work:
> 
> ```diff
> - return TypeDescJS.any(
> -                 TypeDescJS.STRING.or(ctx.javaType(ItemStack.class)),
> -                 TypeDescJS.MAP.withGenerics(TypeDescJS.STRING.or(ctx.javaType(JsonObject.class)))
> -         );
> + return TypeDescJS.any(
> +                 TypeDescJS.STRING, 
> +                 ctx.javaType(ItemStack.class), 
> +                 TypeDescJS.fixedArray(
> +                         TypeDescJS.STRING,
> +                         ctx.javaType(JsonObject.class)
> +                 ));
> ```

It should work.

**Comment by Notenoughmail** [comment]
Thank you for reporting!
